Import modules

In [1]:
import myosuite
import gym
import skvideo.io
import numpy as np
import os
import imageio
import tqdm
import time

MyoSuite:> Registering Myo Envs


Display Settings

In [ ]:
from IPython.display import HTML
from base64 import b64encode

def show_video(video_path, video_width = 400):

  video_file = open(video_path, "r+b").read()

  video_url = f"data:video/mp4;base64,{b64encode(video_file).decode()}"
  return HTML(f"""<video autoplay width={video_width} controls><source src="{video_url}"></video>""")


<h2> Load Policy </h2>
<p>This code specifically uses unpickling to get the policy (mjrl). </p>
<p>Note: The policy is /policies/gaussian_mlp.py </p>

In [ ]:
env = gym.make('CenterReachOut-v0')
policy = "trying2.pickle" #Change the folder to the policy location

import pickle
# load policy
pi = pickle.load(open(policy, 'rb'))

#pi is the trained policy neural network

all_rewards = []

frames = []
for _ in range(1): # 20 random targets
  env.reset()
  ep_rewards = []
  done = False
  obs = env.reset()
  while not done:
      o = env.get_obs()
      # get the next action from the policy
      action, _ = pi.get_action(o)
      # take an action based on the current observation
      obs, reward, done, info = env.step(action)
      ep_rewards.append(reward)
  all_rewards.append(np.sum(ep_rewards))

print(f"Average reward: {np.mean(all_rewards)} over 20 episodes")


env.close()


Average reward: 349.9476727641786 over 20 episodes


### Camera Id's:
// 0 - Side facing
// 1 - Front facing
// 2 - Above facing

In [ ]:
# Use sleep if you want to examine certain steps during the episodes
from time import sleep

print(type(pi))

# Render trained policy
frames = []
for _ in range(20): # 5 random targets
  env.reset()
  print("episode ", _, ":")
  print(env.obs_dict['palm_pos'])
  print(env.current_object_pos)
  ep_rewards = []
  done = False
  obs = env.reset()
  for _ in range(20):
      frame = env.sim.renderer.render_offscreen(
                        width=400,
                        height=400,
                        camera_id=1)
      frames.append(frame)
      o = env.get_obs()
      # get the next action from the policy
      action, _ = pi.get_action(o)
      #print(pi.show_activations())
      #print(pi.get_neurons())
      # take an action based on the current observation
      obs, reward, done, info = env.step(action)

env.close()

os.makedirs('videos', exist_ok=True)
video_path = 'videos/test_policy.mp4'
# make a local copy
imageio.mimsave(video_path, frames, fps=30)
show_video('videos/test_policy.mp4')

<class 'mjrl.policies.gaussian_mlp.MLP'>
episode  0 :
[-0.2391 -0.2395  1.0523]
[-0.05, -0.4, 1.09]
episode  1 :
[-0.2391 -0.2395  1.0523]
[-0.05, -0.1, 1.09]
episode  2 :
[-0.2391 -0.2395  1.0523]
[-0.2, -0.2, 1.09]
episode  3 :
[-0.2391 -0.2395  1.0523]
[-0.05, -0.1, 1.09]
episode  4 :
[-0.2391 -0.2395  1.0523]
[0.1, -0.1, 1.09]
episode  5 :
[-0.2391 -0.2395  1.0523]
[0.1, -0.1, 1.09]
episode  6 :
[-0.2391 -0.2395  1.0523]
[0.1, -0.3, 1.09]
episode  7 :
[-0.2391 -0.2395  1.0523]
[-0.05, -0.1, 1.09]
episode  8 :
[-0.2391 -0.2395  1.0523]
[0.1, -0.3, 1.09]
episode  9 :
[-0.2391 -0.2395  1.0523]
[-0.15, -0.1, 1.09]
episode  10 :
[-0.2391 -0.2395  1.0523]
[0.15, -0.2, 1.09]
episode  11 :
[-0.2391 -0.2395  1.0523]
[-0.05, -0.1, 1.09]
episode  12 :
[-0.2391 -0.2395  1.0523]
[-0.15, -0.3, 1.09]
episode  13 :
[-0.2391 -0.2395  1.0523]
[-0.2, -0.2, 1.09]
episode  14 :
[-0.2391 -0.2395  1.0523]
[-0.05, -0.1, 1.09]
episode  15 :
[-0.2391 -0.2395  1.0523]
[-0.05, -0.1, 1.09]
episode  16 :
[-0.23